
GET http://localhost:3100/api/v2/auth/all-users

###
POST http://localhost:3100/api/v2/student/register
Content-Type: application/json

{
     "surname": "Sammy",
      "othernames":"Doe",
     "email":"xyz@email12.com",
      "classLevels":"",
      "dateOfBirth":"2022-09-11",
      "sex":"male",
      "parentSurname":"James",
      "parentOthernames":"Doew",
      "parentOccupation":"DEV",
      "phone":"09087652333",
      "address":"Home",
      "healthStatus":"Healthy",
      "religion":"Christainity",
      "entrySession":"2023/2024"
}

###
GET http://localhost:3100/api/v2/student/get-student/66360a5b7f1132cf71a74f68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTcyMjQ4LCJleHAiOjE3MTUxNzI4NDh9.XB7QUyJAoQE3OspSW4AcHrtKQpEGWTX5Zx01eC4Ee3A


###
GET http://localhost:3100/api/v2/student/all-students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTcyMjQ4LCJleHAiOjE3MTUxNzI4NDh9.XB7QUyJAoQE3OspSW4AcHrtKQpEGWTX5Zx01eC4Ee3A

###
POST http://localhost:3100/api/v2/student/login
Content-Type: application/json

{
    "username":"STU51715S",
    "password":"sammy"
}


###
POST http://localhost:3100/api/v2/auth/refresh
Content-Type: application/json
{
      "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzYwYTViN2YxMTMyY2Y3MWE3NGY2OCIsInVzZXJuYW1lIjoiU2FtbXkgRG9lIiwiaWF0IjoxNzE0OTkzMTg0fQ.M09EMvOyn3ldLGZJoesESHq8E7NSjQ5JLLZFHZ9Nb_k"

}

###
POST http://localhost:3100/api/v2/admin/create-admin
Content-Type: application/json

{
    "username":"xyz",
    "password":"password",
    "surname":"John",
    "othername":"Doe",
    "email":"xyz@example.com"

}

###
GET http://localhost:3100/api/v2/admin/all-admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTY2ODY3LCJleHAiOjE3MTUxNjc0Njd9.CnRGk-rxXBg5D0jAn7wNXZ_nMqe4QkPSoBpz5SefC0M


###
PUT http://localhost:3100/api/v2/admin/update-admin/65f6ec2ea188a6d614f60173
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTY2ODY3LCJleHAiOjE3MTUxNjc0Njd9.CnRGk-rxXBg5D0jAn7wNXZ_nMqe4QkPSoBpz5SefC0M

{
    "username":"adminUpdated"
}

###
DELETE http://localhost:3100/api/v2/admin/delete-admin/663b430b3278afd855251b84
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTY2ODY3LCJleHAiOjE3MTUxNjc0Njd9.CnRGk-rxXBg5D0jAn7wNXZ_nMqe4QkPSoBpz5SefC0M


###
GET http://localhost:3100/api/v2/admin/get-admin/663b4129108cb5e008e4fcfb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2I0N2VkOGM2YjUyYjY2ZjI3MWQwMiIsInVzZXJuYW1lIjoiSm9obiB1bmRlZmluZWQiLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNzE1MTY2ODY3LCJleHAiOjE3MTUxNjc0Njd9.CnRGk-rxXBg5D0jAn7wNXZ_nMqe4QkPSoBpz5SefC0M


###
POST http://localhost:3100/api/v2/admin/login
Content-Type: application/json

{
    "username":"xyz",
    "password":"password"
}